- src/common/text.c
> Fix incorrect timestamp in scrollback with server-time

- Makefile.am
- data/Makefile.am
- data/icons/Makefile.am
- data/misc/Makefile.am
- plugins/fishlim/Makefile.am
- src/common/Makefile.am
- src/fe-gtk/Makefile.am
- src/fe-text/Makefile.am
Fix some 'make dist' issues to create a working tarball.
Making 'make distcheck' work is another story though.
> build: Let 'make dist' do a better job

- src/common/outbound.c
Noticed that there is no MHOP command. Given that there is a MOP, MDEOP and MDEHOP it seems like the useful MHOP command is missing. I have added it in.
> Added MHOP command

- configure.ac
> Fix bashism

- src/htm/Main.cs
> thememan: Check for portable-mode file in the application directory.

- src/fe-gtk/notifications/notification-backend.h
- src/fe-gtk/notifications/notification-windows.c
- src/fe-gtk/notifications/notification-winrt.cpp
- src/fe-gtk/plugin-notification.c
> winrt: Show some exceptions

- src/common/hexchat.c
- src/fe-gtk/joind.c
- src/fe-gtk/menu.c
- src/fe-gtk/servlistgui.c
- src/fe-gtk/setup.c
I've probably forgotten something, please let me know.
> UI text consistency, capitalization etc.

- src/fe-gtk/setup.c
As per https://en.wikipedia.org/wiki/SOCKS
> Spelling: SOCKS5, Byte per second

- src/common/util.c
Implementation of rfc_casecmp sourced from TingPing.
> Fix rfc_{n,}casecmp functions

- plugins/python/python.py
Quick ease of use change, shows devs where the error on import occurred
> made tracebacks be printed on load and unload errors

- plugins/python/python.py
Adjust the width of the columns depending on the length of the data in
each element.
> Make the python plugins table dynamically sized

- plugins/python/_hexchat.py
- plugins/python/python.py
- plugins/python/python_style_guide.md
Fixes some readability, removes some inefficient code
> Python plugin cleanup

- src/fe-gtk/fe-gtk.c
> Extend Adwaita workaround [#2305]

- src/common/server.c
If a user has a large number of channels containing hyphens in their names, the initial MODE queries will have the same high priority as any PINGs, and so will block the PINGs from being sent, causing the connection to time out due to a lack of PONGs received.
> Avoid prioritising MODE queries for channels with hyphens in their name

- src/common/servlist.c
According to [netsplit.de's top 100 list](https://netsplit.de/networks/top100.php) "DarkScience" is ranked 66 for number of users.
Notably hosting the [Hak5](https://hak5.org) and [joinmarket](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/293/files#diff-4f3c2beacd536175f30616463ddaeb33) communities, along with the social aspect of the network itself.
The environment surrounding the network is one of good standing and has a fair reputation of legal and ethical behaviour.
I think this is a fair addition to the list, please let me know if there are any concerns. :)
> Add "DarkScience" to default server list.

- plugins/lua/lua.c
Closes #2558
Co-authored-by: "Jan Alexander Steffens (heftig)" <jan.steffens@gmail.com>
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
> plugins/lua/lua.c: fix segfault on lua_pop with Lua 5.4.3

- src/common/servlist.c
> add tilde.chat

- src/common/inbound.c
- src/common/proto-irc.c
- src/common/userlist.c
Exactly what it says on the tin.
> Implement support for the IRCv3 SETNAME specification.

- src/common/inbound.c
- src/common/proto-irc.c
- src/common/text.c
- src/common/textevents.in
Exactly what it says on the tin.
> Implement support for the IRCv3 invite-notify specification.

- plugins/python/python.py
The range goes from 31 to 1 inclusive (#2391).
> python: Fix off by one range

- src/common/modes.c
https://ircv3.net/specs/extensions/utf8-only
> Implement support for the IRCv3 UTF8ONLY specification.

- src/common/proto-irc.c
- src/common/text.c
- src/common/textevents.in
Not much is really done with them currently other than printing them in a user-readable way but later specs may require special handling.
https://ircv3.net/specs/extensions/standard-replies
> Implement generic support for IRCv3 standard replies.

- src/common/proto-irc.c
This fixes showing the set time of bans on ban lists.
> Fix parsing +beI lists on InspIRCd.

- plugins/python/python.py
closes https://github.com/hexchat/hexchat/issues/2690
> fix addons load in python2

- .github/workflows/windows-build.yml
- win32/hexchat.props
- win32/installer/hexchat.iss.tt
Switched to Python 3.8.2 and resolved some `FIXME` sections in python plugin.
should close #2438.
Note:
AppVeyor must be switched to python 3.8.2 for it to pass.
> updated python3 to 3.8.10

- src/common/cfgfiles.c
- src/common/hexchat.h
- src/fe-gtk/maingui.c
- src/fe-gtk/setup.c
For https://github.com/hexchat/hexchat/issues/2757
> Add option to exclude nickname in window title

- data/misc/io.github.Hexchat.ThemeManager.desktop.in
Otherwise it looks awkward on my DE without a description.
> Add description for .desktop file for HexChat thememan

- src/common/inbound.c
- src/common/scram.c
- src/common/scram.h
- src/common/server.c
A few improvements requested by Nei. They are not finish yet, so I keep this PR as draft.
> SCRAM: Small bugfixes
