src/common/servlist.c

I'm removing Seion from the serverlist because it's now mostly a defunct network. One of the servers is completely broken in regards to ipv6 connectivity and SSL, the webchat server hasn't worked for months, and I shut down my server (fox.seion.us) a few days ago.

Removed SeionIRC from the serverlist

---

src/common/server.c

This is needed so the server can choose the right certificate to send, or so it knows what host or service to forward the connection to.
I didn't bother checking the function return status because it doesn't really matter, it'd only fail for SSLv3 or lower connections which no one should be using anyway, though the program should still proceed just without SNI.

TLS: Set SNI hostname before connect

---

src/fe-gtk/fkeys.c

If you are talking with someone else with the same prefix as your
own nickname, and attempt to tab complete theirs. It will complete
your own nickname before theirs if you talked more recently. Since
people rarely intend to highlight themselves, this improves the
logic to complete your own name only as a last resort.

Make tab completion prefer other people

---

plugins/sysinfo/osx/backend.m

Use the (deprecated) Gestalt functionality for fetching the fine-grained
OS X version number on 10.9 and lower.
The newer NSOperatingSystemVersion structure is only available on
10.10+.

sysinfo: fix compilation on OS X 10.9 and lower.

---

plugins/sysinfo/osx/backend.m

`MAC_OS_X_VERSION_MAX_ALLOWED` reflects the currently running OS X version
more closely than `MAC_OS_X_VERSION_MIN_REQUIRED`, given it's defined as
`max(current_version, MAC_OS_X_VERSION_MIN_REQUIRED)`.
Additionally, we should check if `MAC_OS_X_VERSION_10_9` is actually
defined, otherwise the whole macro logic breaks apart.

sysinfo: fixup 49758cafba9fd7e0663b550debfd51fb21260650.

---

src/common/inbound.c
src/common/userlist.c

Only update usercount once instead of the (number of users) times per nameslist in channels.

Update usercount in title and userlist label only once

---

plugins/mpcinfo/oggInfo.c

Modification of string literals causes undefined behavior: http://stackoverflow.com/questions/8302290/why-does-char-cause-undefined-behaviour-while-char-doesnt

mpcinfo: Do not modify string literals

---

src/fe-gtk/menu.c

Multiple of my friends and I are big HexChat users and we always run into the issue of hitting ctrl+w accidentally (same shortcut as closing a browser window) as we misjudge the current in-focus window. As a result, many annoyances were shed. 
It seems like many other users share this gripe as well: https://github.com/hexchat/hexchat/issues/397
I understand better key-binding optimization may or may not come, so the proposal here is to disable it as a behavior overall. Perhaps when better key-binding customization is supported, users can choose themselves whether or not to enable this shortcut. 
Note this has nothing to do with the ctrl+q behavior.

Removed ctrl+w keybinding

---

src/common/url.c

I can't found any documents about "email address can not starts with digit".  And in the real world, email address that starts with digit is widely used (such as qq mail provided by Tencent).

Fix email address pattern, it can starts with digit

---

plugins/fishlim/dh1080.c

Clients will receive the proper shared secret.
Eliminates error message:
SSL_read: error:05066064:Diffie-Hellman routines:compute_key:no private value

Fix key exchange

---

.editorconfig

This allows multiple editors (see http://editorconfig.org/ for the full list) to automatically use the correct indenting style.

Add editorconfig, describing what indenting style to use.

---

src/common/servlist.c

Should fix out of range from #1999

servlist: skip empty lines.

---

src/common/inbound.c

If ptr[0] is NULL, then strchr may return a pointer to the NULL
terminator for serv->nick_prefixes, making the if statement true, which
then leads to the pointer increment leaving ptr oob. Now we check to
ensure ptr[0] != NULL.
From the Linux manpages for strchr:
The terminating null byte is considered part of the string, so that if c is
specified as '\0', these functions return a pointer to the terminator.
This fixes the underlying issue that I was attempting to fix in #2058, which did not actually fix the issue since the pointer is already oob by the time we get to rfc_casecmp as a result of the inbound_notice code, which I fix here.

Fix oob read caused by ptr[0] being NULL in inbound_notice

---

src/common/util.c

If n becomes 0 at the same time that the end of either s1 or s2 are
reached, the next iteration of the while loop wouldn't happen, so we
wouldn't correctly return 0.

Fix rfc_ncasecmp handling of n reaching 0

---

src/common/cfgfiles.c
src/common/hexchat.h
src/common/server.c

This change adds an option `irc_reconnect_rejoin` (default ON)
which when turned OFF will prevent hexchat from rejoining channels
after an auto reconnect.
hexchat/hexchat#2069

Add an option to disable rejoin on auto reconnect

---

src/common/ctcp.c

word[4] can be too short, leading to the addition of ctcp_offset
putting us out of bounds. This results in an oob read in ctcp_check.

Fix oob read in ctcp_check

---

src/fe-gtk/xtext.c

`gtk_xtext_append_indent` is getting passed `left_text = 0` and `left_len = 0` from `PrintTextLine`, so `memcpy` is being called like `memcpy(str, 0, 0)` which is undefined behaviour.

Prevent undefined behaviour on memcpy

---

src/fe-gtk/xtext.c

This patch hopefully solves a bug that causes that when a tab (channel or private) is left with the scrollbar at the bottom, and some new text arrives, and then we select again that tab, sometimes the scrollbar is not completely down and there is hidden text and we have to scroll manually to the bottom to show all text.
This was previously submitted as an issue in: https://github.com/hexchat/hexchat/issues/1948
Maybe it isn't the ideal way to solve it, but at least I tested it and it seems to work.

Always keep the scrollbar at the bottom if it was before

---

data/misc/meson.build

The path where appdata/appstream files should be installed has been
changed from /usr/share/appdata/ to /usr/share/metainfo/.
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location
I don't know *when* it happened, but in Debian we had a check for this since some time already.
Also note, I didn't try to build the project and see whether it does what I expect to.

Change the installation path of the appdata file to {datadir}/metainfo

---

plugins/perl/meson.build

With the switch to meson, the problem previously fixed in #1822 came
back. The build system might pick up the installed hexchat-config.h
instead of using the header in the source directory, as the compiler
arguments would be in the order of "-I${prefix}/include -I..".
It seems that the c_args in meson are always put to the front of the
compiler arguments, in order to be able to override any include paths
from dependencies. However, this was not the intention here, so perl
should also be modeled as a dependency. This ensures that the arguments
with local include directories come first.

build: perl as a dependency in meson.build

---

src/common/outbound.c
src/common/plugin.c
src/common/plugin.h
src/fe-gtk/plugingui.c

The switch to the meson build system broke plugins on macOS. GNU libtool
builds shared libraries with ".dylib" and shared modules (plugins) with
the extension ".so", but meson is using ".dylib" for both.
Although overriding the name_suffix for shared_module() in meson is
possible, this would be messy for other platforms as there is no way to
query the default. Therefore it seems like we have to go with ".dylib"
for now on macOS.
However, G_MODULE_SUFFIX is defined to ".so", because glib follows what
GNU libtool does. Therefore define a separate preprocessor macro that
has the correct extension.
See: https://github.com/mesonbuild/meson/issues/1160

Fix plugins on macOS

---

plugins/python/python.py

`/py exec` was previously syntax erroring when something like `/py exec import sys; print(sys.modules)` was run

fix /py exec behaviour

---

plugins/python/python.py

resolves issues where using 'multiline' statements cause syntax errors:
```python
From cffi callback <function _on_py_command at 0x7f29afe40378>:
Traceback (most recent call last):
File "<init code for '_hexchat_embedded'>", line 411, in _on_py_command
File "<init code for '_hexchat_embedded'>", line 369, in exec_in_interp
File "<init code for '_hexchat_embedded'>", line 100, in compile_line
File "<string>", line 1
for x in "test": print(x)
^
SyntaxError: unexpected EOF while parsing
```

fixed /exec behaviour (again)

---

plugins/python/python.py

Added a print for reloading a plugin that doesnt exist. This copies previous behavior and stops confusion

added error for bad reload

---

src/common/server.c

When connecting on SSL, the verify in the context is setup too late and does not affect the existing ssl. This creates an inconsistent behavior because the first time an SSL connection is established it won't call the verification callback:
`[17:46:40] * Looking up irc.freenode.net`
`[17:46:42] * * Certification info:`
`[17:46:42] *   Subject:`
`[17:46:42] *     CN=weber.freenode.net`
The second time is called because the context was configured from the first time:
`[17:46:47] * Looking up irc.freenode.net`
`[17:46:48] * * Subject: /O=Digital Signature Trust Co./CN=DST Root CA X3`
`[17:46:48] * * Issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3`
`[17:46:48] * * Subject: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3`
`[17:46:48] * * Issuer: /O=Digital Signature Trust …

Fix inconsistent behavior (re)connecting on SSL

---

plugins/sysinfo/meson.build

'gnu' => Hurd
'gnu/' => all the gnu/* stuff like gnu/kfreebsd

Fix compilation failure on non-linux, non-darwin, non-windows systems.

---

plugins/python/python.py

Name set to match [old behavior](https://github.com/hexchat/hexchat/blob/02c92599faa8adbe8710177f943c3ca3cb4a65d9/plugins/python/python.c#L2693)

made sure to set sys.argv if it is not set. fixes #2282

---

plugins/python/python.py

Replace `pydoc.help` with a copy of `pydoc.Helper` with an empty
`StringIO` instead of stdin

Make sure `help()` doesn't cause hexchat to hang

---

src/common/modes.c
src/common/proto-irc.c
src/common/proto-irc.h

Partial fix for #2271 
This isn't an exhaustive list, but it's everything I could find. The bug still exists in the parser though, this is just a workaround for the moment

Remove : from various trailing parameters

---

src/common/servlist.c

Update to servlist.c, removes 3 lines for furnet; fixes #2324

Update servlist.c - Fixes #2324

---

src/common/servlist.c

- requires the use of TLS to connect on port 6697
- supports and encourages authentication via SASL PLAIN and EXTERNAL
Certificates used are signed by Let's Encrypt.

servlist: add hackint irc network

---

src/common/dcc.c
src/common/dcc.h
src/common/hexchat.h
src/common/inbound.c
src/common/outbound.c

Moved dcc_ip from prefs to sess->server.
Currently the DCC IP address is a global setting in Preferences. It can be set globally, and optionally, the IP address can be acquired from the IRC server. Currently only a single IP address can be stored, the last detected IP address wins.
When using multiple IRC servers or networks from which at least one is available via VPN while the other use Internet, only the last detected IP address is stored, causing DCC not working with autodetected IP address on the first-connected IRC server or network.
This change makes dcc_ip a server property, allowing per-server record of the detected address. Very useful when both "VPN" and "Internet" connections use dynamic addresses.
The global setting still overrides it, if set.

Make dcc_ip being a per-server value.

---

plugins/python/_hexchat.py

Fixes exception in hexchat_emit_print, was causing my buffextras script to break. Only breaks in latest master, not in 2.14.2.
Command to reproduce error:
/py exec hexchat.emit_print("Change Nick", "fakeuser1", "fakeuser2", time=1)

Python: Fix error in hexchat.emit_print when passing time attribute

---

src/common/meson.build

I'm staring at this build error:
~~~
[1/74] Compiling C object 'plugins/fishlim/c61e818@@fishlim@sha/irc.c.o'.
[2/74] Compiling C object 'plugins/fishlim/c61e818@@fishlim@sha/fish.c.o'.
[3/74] Compiling C object 'plugins/fishlim/c61e818@@fishlim@sha/dh1080.c.o'.
[4/74] Compiling C object 'plugins/fishlim/c61e818@@fishlim@sha/keystore.c.o'.
[5/74] Generating resources_h with a custom command.
[6/74] Generating resources_c with a custom command.
[7/74] Compiling C object 'plugins/fishlim/c61e818@@fishlim@sha/plugin_hexchat.c.o'.
[8/74] Compiling C object 'plugins/checksum/c016833@@checksum@sha/checksum.c.o'.
[9/74] Linking target plugins/checksum/checksum.so.
[10/74] Linking target plugins/fishlim/fishlim.so.
[11/74] Compiling C object 'src/fe-text/cdba4cc@@hexchat-text@exe/fe-text.c.o'. …

build: Make generated headers a dependency for users of common.

---

plugins/sysinfo/shared/df.c

Generally, how much space we have in squashfs, or tmpfs shouldn't
interest us. This becomes more relevant in distros like Ubuntu, where
snaps are a thing, and each snap mounts their own FS in a squashfs that
is always full, thus falsifying the output of sysinfo.
Some other things to consider, where I haven't found a good solution yet: ZFS. On my desktop, I have a ZFS array for data storage, and that makes the df-output go a little crazy and yield very wrong results, which would require significantly more complex parsing and detection. Example:
```
Filesystem                        Size  Used Avail Use% Mounted on
desktop-zfs-crypt/misc            510G  133M  510G   1% /home/simon/misc
desktop-zfs-crypt/videos          2,2T  1,7T  510G  78% /home/simon/Videos
desktop-zfs-crypt/bitcoin …
```

Ignore some non-interesting filesystem types in sysinfo plugin

---

src/fe-gtk/maingui.c

Without the include gcc will complain about WM_TIMECHANGE as undeclared.

Add include for winuser.h for mingw compilers.

---

src/common/hexchat.h
src/common/server.c

Updated the maximum length of the socks5 user and password to comply to RFC 1929, where both the password and the username length is defined as a maximum of 255.
This PR is based on #1994 (thanks @kelek-) and will resolve #1296.

Socks5 user pass limit

---

src/common/servlist.c

Mozilla's Moznet no longer exists. They migrated to Matrix.
> Note that on 2nd March 2020, Mozilla moved away from IRC to Matrix for its public channels, the IRC server was be shut down.
Source: https://wiki.mozilla.org/IRC

Remove Moznet

---

src/fe-gtk/maingui.c

winuser.h should never be included directly. windows.h should be included instead.
This fixes a critical build issue added in c5d47fc which makes all MinGW builds fail.
See #2403.

win32: Replace include of winuser.h with windows.h

---

src/fe-gtk/meson.build

Windows builds of the GTK frontend use the pie flag to compile
hexchat.exe. Windows needs an explicit entrypoint when compiling with
--pie, otherwise an invalid executable is created.
This sets the entrypoint of the executable on Windows (as it is
currently set in the Visual Studio project files).
This fixes a critical build issue which prevents all Windows builds using
Meson from working.

win32: Fix building executables with invalid entrypoints

---

meson.build

GDB is usually able to debug executables with ASLR by temporarily
disabling ASLR when running that executable. This is only supported on
Linux. On Windows, GDB cannot debug ASLR executables.
This removes the dynamicbase linker flag on Windows for debug builds in
order to be able to debug that executable later.
Hardening an executable with ASLR is important for release builds, but
for debug builds being able to debug is much more important.

win32: Disable ASLR for Windows debug builds

---

src/common/plugin.c

Windows builds without plugins can use notification-windows.c, which
uses module_load in its notification_backend_init function.
module_load was previously guarded with a USE_PLUGIN ifdef, but we do
need this function for Windows builds even if plugins are disabled.
This fixes a critical build issue for all Windows builds without
plugins.

win32: Fix undefined symbol for builds with -with-plugin=false

---

src/common/inbound.c

there's 2 reasons for this
- SASL `EXTERNAL` could be something other than certificate
- not even trying SASL `EXTERNAL` when there's no cert means there's no SASL failure in logs

SASL EXTERNAL doesn't necessitate a certificate

---

src/fe-gtk/menu.c

When the channel is focussed, the menu item does nothing so
it isn't useful to have it in the menu.
Fixes: commit c361bdca6afdc933eeac35732334464990295cd4
See-also: https://github.com/hexchat/hexchat/pull/2255#issuecomment-475841824

Hide Focus Channel when the selected channel is already focussed

---

src/fe-gtk/xtext.c

With newer versions of Pango and some fonts, the bottom of the
text is clipped (making underscores invisible). Use the correct
calculation when needed to avoid this.
Based on an original fix by Jeff Teunissen.
Closes #2449.

Use pango_font_metrics_get_height() to calculate font height

---

src/fe-text/fe-text.c

There is a small typo in src/fe-text/fe-text.c.
Should read `worry` rather than `wory`.

docs: fix simple typo, wory -> worry

---

src/common/url.c

This PR adds URL parsing support for two "small-Internet" protocols, [Gemini](https://gemini.circumlunar.space/) and [Gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)). This is especially useful for those of us who discuss these particular protocols over IRC!
Example URLs:
* gemini://gemini.circumlunar.space
* gopher://sdf.org

url.c: add gemini & gopher parsing

---

src/fe-gtk/pixmaps.c

Currently on Linux (Ubuntu 21.04 in my case) HiDPI screens icons are not rendered at the correct size. This is problematic if you have a HiDPI screen because icons are just completely invisible. Unfortunately because HexChat uses GTK2 it's not really possible to automatically scale to the screen resolution so this patch adds a workaround by having it check a common environment variable used for UI scaling in GDK3 and then scaling the icons by that size on load.
Without this patch on my system:
With this patch and GDK_SCALE=3 set in the environment on my system:
If anyone can recommend a better way of doing this then I'll be happy to change this.

Add a workaround for icons not scaling right on HiDPI screens.

---

src/common/hexchat.h
src/common/inbound.c
src/common/proto-irc.c
src/common/proto-irc.h
src/common/server.c
src/common/userlist.c

Exactly what it says on the tin.
This probably conflicts with #2571 but I can resolve that if necessary.
---
One thing that could be improved with this is unsetting the user's account if the cap is enabled but the tag isn't sent. I'm reasonably sure that this is possible but I haven't verified that all servers send the tag on all messages yet.

Implement support for the IRCv3 account-tag specification.

---

src/common/servlist.c

Added the LibertaCasa IRC network  (single master server) and TripSit IRC network (round-robin, master, and slave servers).

Adding LibertaCasa + TripSit to servlist.c

---

src/common/servlist.c

Website: https://irc.acn.gr
Round-Robin DNS: global.acn.gr
Ports: 6667 - 6697(ssl only).

Add ACN IRC Network

---

src/common/modes.c

This implements support for the full 005 numeric syntax including negation and value escapes as defined in [draft-hardy-irc-isupport-00](https://datatracker.ietf.org/doc/html/draft-hardy-irc-isupport-00). This fixes HexChat on servers that:
1. Have unloaded a previously supported feature at runtime (e.g. unloading the monitor module in InspIRCd removing the MONITOR token).
2. Have escaped spaces in the network name (see testnet.inspircd.org for an example of this).
3. Send a value for a token where HexChat expects none (e.g. INVEX on InspIRCd &mdash; the value for this token is optional) or vice versa.

Parse the output of the 005 numeric correctly.

---

src/common/inbound.c

if the front buffer is on the same network.

Place ChanServ notices in the front buffer

---

src/common/outbound.c
src/common/servlist.c
src/fe-gtk/servlistgui.c

1. If built with OpenSSL then tick the box for using SSL by default in the server list and use the typical SSL port in the example.
2. If connecting with SSL via a command then enable certificate validation by default. This can be opted-out of by using `-ssl-noverify` instead of `-ssl`.

Make default connection behaviours more secure

---

plugins/fishlim/plugin_hexchat.c
src/common/ctcp.c
src/common/hexchat.h
src/common/inbound.c
src/common/proto-irc.c
src/common/proto-irc.h

Now that freenode has committed suicide there's no significant users of ircd-seven. This means that there's essentially no point to supporting the ircd-seven specific identify-msg cap.
However, the successor to ircd-seven, Solanum, which is currently used by Libera Chat and will be used by OFTC in the future has a replacement for it which uses a cap instead of message prefix which removes the need do the messy character skipping logic. Cool!

Replace identify-msg support with solanum.chat/identify-msg.

---

src/common/outbound.c
src/common/util.c
src/fe-gtk/maingui.c
src/fe-gtk/sexy-spell-entry.c
src/fe-gtk/xtext.c
src/fe-gtk/xtext.h

https://defs.ircdocs.horse/info/formatting.html
Note: this would be cleaner if `pango_attr_strikethrough_new` actually worked in the chat box but it doesn't so I copied the underline code which manually draws the underline (presumably because `pango_attr_underline_new` also doesn't work).
I have a second branch locally which implements strikethrough with the Pango method which is less hacky if the reason why it can't draw to the chat box can be determined.
P.S. Sorry if the amount of PRs is a bit overwhelming. I'll hold off on submitting any more for a while so you have time to catch up.

Implement support for strikethrough text.

---

src/common/servlist.c

Added 1 server to Aitvaras
Added 1 server to EFNet
Added 2 servers to chatpat (previously UniBG)
Added DosersNET
Put network list into alphabetical order.
Removed 2 servers from EFNet
Removed 3 servers from Aitvaras
Removed 3 servers from chatpat (previously UniBG)
Removed AccessIRC (no longer exists)
Removed BetaChat (no longer exists)
Removed Buddy.IM (no longer exists)
Removed ChatNet (no longer exists)
Removed ChattingAway (no longer exists)
Removed Criten (connects to Rizon)
Removed DeltaPool (zero connections and channels)
Removed ElectroCode (no longer exists)
Removed GalaxyNet (no longer exists)
Removed GeeksIRC (no longer exists)
Removed IdleMonkeys (no longer exists)
Removed IndirectIRC (no longer exists)
Removed iZ-smart.net (no longer exists)
Removed ObsidianIRC (no longer …

Update servlist.c - Network clean up

---

meson.build
meson_options.txt
src/common/hexchat.c
src/common/meson.build
src/common/server.c
src/fe-gtk/setup.c

Since hexchat already depends on GLib, it's better to use GProxyResolver
instead. This might use libproxy, or not, as appropriate.
P.S. This removes a memory safety issue because proxy_list is allocated
using malloc(), not g_malloc(), and therefore using g_strfreev() is
incorrect. The proper way to free the proxy list returned by libproxy
is to use px_proxy_factory_free_proxies() (but nobody does that because
it was added in libproxy 0.4.16, which is somewhat recent).
Note: libproxy is not used by default. It's only used if the proxy type setting in Preferences is switched to Auto, i.e. `net_proxy_type = 5` in hexchat.conf. I didn't test hexchat with an actual proxy server (who uses proxies in 2021?) but I did test that the proxy variables in server_child() get set properly by adding a …

Avoid direct use of libproxy

---

src/common/modes.c
src/common/proto-irc.c
src/common/server.c

Bahamut and ircu both send 005 MODES and ELIST so this is entirely unnecessary. The other IRCd checked for here is for a dead network.
While we're editing this code fix HexChat on servers that can only support one mode at a time (these are mostly gateway servers).

Remove some weird guesswork on the 004 numeric.

---

src/common/hexchat.h
src/common/server.c

In addition to the 512 bytes specified by RFC 1459 IRCv3 message tags can add up to 8191 extra bytes of data to a message. This means that the previous limit of 4096 is far too small to hold an IRC message whilst requesting caps that enable tags,

Increase the linebuf length to fit a full message including tags.

---

src/common/modes.c

The `PREFIX` key in `ISUPPORT` (usually) takes the form
`(modes)prefixes` e.g. `(ov)@+`. The current implementation will
therefore set `serv->nick_modes` to a string like `"(ov"` instead
of the desired `"ov"`. This causes the nick list to not properly
update with which users have which prefix modes. Skip over the
initial `'('` so we capture the correct modes and fix that issue.
Fixes #2599

Fix user list not tracking mode changes

---

plugins/fishlim/fish.c
plugins/fishlim/fish.h
plugins/fishlim/plugin_hexchat.c
plugins/fishlim/tests/tests.c

OpenSSL 3.0 disables a number of "legacy" algorithms by default, and we
need to enable them manually using their provider system. Note that
explicitly loading a provider will disable the implicit default
provider, which is why we need to load it explicitly.
Closes #2629
Signed-off-by: Simon Chopin <simon.chopin@canonical.com>

fish: enable the legacy provider if build against OpenSSL3

---

.github/workflows/flatpak-build.yml
.github/workflows/msys-build.yml
.github/workflows/ubuntu-build.yml
.github/workflows/windows-build.yml

Previously every build showed up in the CI as "build".
Update the job names to reflect what they are. For example the Ubuntu
build is now called "ubuntu_build"

Make build job names more descriptive

---

src/common/outbound.c

This command doesn't have many legitimate, non-spam applications and is
easily confused for the similarly named 'wallops'. Moreover, many
networks now automatically punish or drop users who message many
channels at the same time, rendering the command mostly useless.
It also is too easy to tab-complete 'wall' into 'wallchan' when you
expect 'wallops' to come up first, which can lead to two very different
functions. If this is to be reintroduced it should be named something
with less similarity to 'wallops' or 'wallchops'.

Remove wallchan command

---

plugins/python/meson.build

This fixes loading python plugin in Windows by exporting functions using
python.def file. Otherwise, hexchat_plugin_init symbol error is shown.

meson: Fix exported functions for python plugin

---

src/common/server.c

Instead of wrapping around, which is not behaviour any reasonable user would expect, just use the default port if above 65535.
Disallow connecting on port 0. This port has special meaning and servers can not listen on it. It is more likely the user just gave an invalid value to the port field as `atoi("invalid") == 0`.

Fix handling invalid ports.

---

src/common/outbound.c

see: [https://github.com/hexchat/hexchat/issues/2666](url)
added two flags to EXECWRITE and cmd_execw
-q : (quiet) to allow suppressing of additional (debug) output at the text box
--  : (stop parsing for further flags) for the edge cases where -q itself migh be part of used data and the user wants to show that at the text box

Add -q/-- flags to /execwrite to EXECWRITE and cmd_execW

---

plugins/lua/lua.c

Consider the following contrived Lua plugin:
```lua
__module_name__ = "buftester"
__module_author__ = "William D. Jones (cr1901)"
__module_version__ = "0.1.0"
__module_description__ = "Test Lua buffers"
function unload_cb()
print(__module_name__ .. ' version ' .. __module_version__ .. ' unloaded.')
end
-- Init
-- Without this, plugin unloads immediately.
hexchat.register(__module_name__, __module_version__, __module_description__)
hexchat.hook_unload(unload_cb)
if hexchat.pluginprefs["init_done"] ~= "true" then
print("Initializing table...")
for i=1,100,1 do
hexchat.pluginprefs["key_" .. tostring(i)] = "value_" .. tostring(i)
end
hexchat.pluginprefs["init_done"] = "true"
end
print(pairs(hexchat.pluginprefs))
for k, v in pairs(hexchat.pluginprefs) do
print(string.format('print string: Key …
```

Return userdata from pluginprefs __pairs metamethod to avoid immediate GC

---

src/common/notify.c

hexchat populates the single linked list `notify_list` defined in
`src/common/notify.c` from `notify.conf` file. Each new line read from
the file is added to the list by `g_slist_prepend()` which adds it to
the front of the list. But in `notify_save()` the list elements are read
from the start to end of the list and written to the `notify.conf`. This
means everytime hexchat is opened and closed, the contents of
`notify.conf` get reversed. This commit creates a
temporary glist in `notify_save()` and applies `g_slist_reverse()` on it
and writes the contents of this reversed list to `notify.conf`. And
solves issue #2680

Reverse the notify.conf linked list before writing

---

src/common/proto-irc.c

This makes it a lot easier for users to actually read by not showing the parameter intended for machine consumption.
Requested by @progval.

Display common help numerics as SERVTEXT.

---

src/common/hexchat.h

This might look like a careless hack, but I did poke around the source code enough to make sure it was really that simple. While not a definitive fix (which would not be very practical), for all purposes mentioned in the issue this will hopefully fix #1296.
I have built and installed the patched version of HexChat locally and, having tested it with some very long passwords, can verify it works for SASL-enabled servers without visible issues.
The `serv->password` field is always filled out using the `safe_strcpy` function like this:
https://github.com/hexchat/hexchat/blob/2638c884797b82054116166523ed35c0e303aaa7/src/common/outbound.c#L3524
This ensures that the string inside `serv->password` is always `sizeof(serv->password)` characters long (currently 86) and null-terminated. Thus making …

Raise the max length of a server password to 1024

---

src/common/inbound.c

- Fix #2705
I tested this locally and it works for me with very long passwords.
Passwords resulting in exactly 400, 800 and 1200 byte long auth strings are handled properly.

Split long SASL auth strings into 400-byte chunks

---

src/common/sysinfo/win32/backend.c

the cpu name might have tailing spaces in Windows, which weren't remove before printing.
closes #2637

fix sysinfo print of cpu name

---

plugins/fishlim/fish.c
src/common/proto-irc.c
src/common/util.c
src/fe-gtk/fkeys.c
src/fe-gtk/xtext.c

- fish.c &mdash; -Wincompatible-pointer-types &mdash; using a pointer pointer when it should just be using a pointer.
- fkeys.c &mdash; -Wmisleading-indentation &mdash; the indentation in STRIP_WHITESPACE was clearly wrong.
- proto-irc.c &mdash; -Wincompatible-pointer-types &mdash; word_eol is never const so we can't use const here.
- util.c &mdash; -Wdeprecated-declarations &mdash; OpenSSL v3 deprecated the raw SHA256 method in favour of a single function.
- xtext.c &mdash; -Wmaybe-uninitialized &mdash; Not all code paths initialize `outofbounds` so it should be initialized to FALSE by default.

Fix various compiler warnings.

---

src/fe-gtk/sexy-spell-entry.c

So far, when configuring multiple spell check languages, Hexchat requires users to separate multiple entries with commas and only commas. This patch allows users to also enter whitespace, e.g.
de_DE, en_US
as is common in many applications.
I believe this patch may resolve issue https://github.com/hexchat/hexchat/issues/2508. I know the current behavior of Hexchat was very confusing to me.

Support whitespace between language codes

---

src/common/modes.c

This capability is the equivalent of the old protoctl token so there's no need to send the old method if the capability is enabled.
This pull request also fixes `PROTOCTL NAMESX` on servers that support protoctl but not capability negotiation.

  Fix PROTOCTL NAMESX and only send when not using `multi-prefix`.

---

src/common/outbound.c

Since commit 747a52aae8806a9072a23ea68212767f352ac431 users have to opt-out of using SSL when creating a new server. This commit makes it so /SERVER also uses SSL by default.
In order to connect insecurely users must now use one of these methods:
/SERVER -insecure irc.example.com
/SERVER irc.example.com -6667
The `-ssl` flag and the `+port` syntax have been retained for compat reasons.
---
This might be a controversial change but I think its worth doing in order to avoid users accidentally connecting insecurely without realising.

Default /SERVER and friends to use SSL when built with OpenSSL.

---

win32/installer/hexchat.iss.tt

will allow the user to control on which of the shortcuts to create:
* start menu - will now show the relevant window
* desktop
* quick launch
* pin to taskbar - added a program for this (syspin)
https://www.technosys.net/products/utils/pintotaskbar
on uninstall, all will be removed on uninstall, including `syspin.exe`
closes https://github.com/hexchat/hexchat/issues/2699

add shortcut options in setup

---

src/common/inbound.c

This allows getting hostname/awaymsg/etc updates for monitored clients which will update the internal cache for that data as well as any queries.
While working on this I also noticed that the user@host in the topic bar of queries was not being updated on CHGHOST so I fixed that as well.

Add support for the IRCv3 extended-monitor specification.

---

src/fe-gtk/chanlist.c
src/fe-gtk/dccgui.c
src/fe-gtk/editlist.c
src/fe-gtk/fe-gtk.c
src/fe-gtk/fkeys.c
src/fe-gtk/ignoregui.c
src/fe-gtk/plugingui.c
src/fe-gtk/setup.c
src/fe-gtk/textgui.c
src/fe-gtk/xtext.c

This is part one of my attempt to port HexChat to GTK 3. It's a pretty big changeset so I have split up my commits to make reviewing easier. This initial pull request just contains the low hanging fruit which can be dealt with whilst still depending on GTK 2.
---
The following functions which were removed/deprecated in GTK+3 have been replaced with their non-deprecated equivalents:
- `gdk_beep` -> `gdk_desktop_beep`
- `get_drawable_get_size` -> `gdk_window_get_width`, `gtk_window_get_height`
- `gtk_widget_is_composited` -> `gtk_screen_is_composited`
The following function have been removed:
- `gtk_tree_view_set_rules_hint` &mdash; this does nothing on GTK3 and also apparently does nothing with a lot of modern GTK2 themes that I have tried.

Migrate to GTK 3: remove deprecated/removed functions

---

plugins/python/python.py

Python sometime calls flush() on sys.stdout or sys.stderr.
In particular, it might do so when an exception is raised. This fixes
the second error message that was generated in such cases.

python: add flush() to Stdout

---

plugins/python/python.py

When a timer hook unhooks itself and return False, the internal code generates an exception about a weakly-referenced object that no longer exists.
I am unsure how it all works. My tests work, but they might not be exhaustive enough.
In particular, I don't understand why setting `hook.is_unload = True` is necessary. But my guess is that this line can be safely ignored when the `Hook` object has already been destroyed, since the only effect it could have had was in `Hook.__del__`. Which won't be called again because the object no longer exists.
I also note that the code relying on `__del__` seems quite fragile. As far as I understand, the python plugin uses weak references to avoid references loops. This lets the CPython garbage collector free the object as soon as the last reference is …

python: fix for timers that unhook themselves
